### ISSUE TITLE
Machine Learning model for text 

### ISSUE THREAD

**Issue by ksreyr** [SantiRey/MLBotApproach#4]
**Description:**
Implementation of Machine Learning models for the prediction of input by a user.
**Relevant Information:**

**Comment by serome111** [comment]
lectura de documento con información previa para de esa información sacar el tipo de tema para que el modelo sepa que tipo de respuestas basadas en el tema encontrado en la información básica suministrada por la empresa.
todo basado en un algoritmo de lematización de palabras del texto 
https://janav.wordpress.com/2013/10/27/tf-idf-and-cosine-similarity/

**Comment by serome111** [comment]
actualmente tenemos un problema de lematización de preguntas, ya que tenemos una respuesta para "cómo comprar" pero "como compro" es lo mismo pero en este punto ya no sabe cómo responder, pero con el uso de lematización podremos hacer que entienda que se habla de lo mismo y tendremos más respuestas para más palabras y no necesitaremos que tener una respuesta exacta en nuestro data set @SantiRey
